title: grokking simplicity notes
email: dev@eunice-hong.com
description: >-
  Notes on grokking simplicity

plugins:
  - jekyll-multiple-languages-plugin

baseurl: /grokking-simplicity
permalink: /:title/

languages: [ "ko", "en" ]
defaultLang: ko
languageNames:
  ko: 한국어
  en: English

exclude: [ "404.html", "README.md", "about.markdown", "package.json", "src", "node_modules", "vendor/bundle" ]
exclude_from_localizations: [ "javascript", "images", "css", "scripts", "favicon.ico", "assets" ]