title: grokking simplicity notes
email: dev@eunice-hong.com
description: >-
  Notes on grokking simplicity
baseurl: ""
plugins:
  - jekyll-feed
relative_links:
  enabled: true
  collections: true
include:
  - README.md
theme: minima
